csdn_urls = {
    'http://blog.csdn.net/qq_15807167': 'mobile', 'http://blog.csdn.net/zhangphil': 'mobile',
    'http://blog.csdn.net/u013263917': 'mobile', 'http://blog.csdn.net/jiangbo_phd': 'mobile',
    'http://blog.csdn.net/qq446282412': 'mobile', 'http://blog.csdn.net/crazy1235': 'mobile',
    'http://blog.csdn.net/sunboy_2050': 'mobile', 'http://blog.csdn.net/wxs0124': 'mobile',
    'http://blog.csdn.net/Double2hao': 'mobile', 'http://blog.csdn.net/q649381130': 'mobile',
    'http://blog.csdn.net/zxt0601': 'mobile', 'http://blog.csdn.net/danfengw': 'mobile',
    'http://blog.csdn.net/xiejiashu': 'network', 'http://blog.csdn.net/erlian1992': 'network',
    'http://blog.csdn.net/xvshu': 'network', 'http://blog.csdn.net/claram': 'network',
    'http://blog.csdn.net/sun7545526': 'network', 'http://blog.csdn.net/wangyangzhizhou': 'network',
    'http://blog.csdn.net/zhangdaiscott': 'network', 'http://blog.csdn.net/mindfloating': 'network',
    'http://blog.csdn.net/breaksoftware': 'network', 'http://blog.csdn.net/vtopqx': 'network',
    'http://blog.csdn.net/Androidlushangderen': 'network', 'http://blog.csdn.net/u010046908': 'network',
    'http://blog.csdn.net/silentwolfyh': 'bigdata', 'http://blog.csdn.net/q383965374': 'bigdata',
    'http://blog.csdn.net/SunnyYoona': 'bigdata', 'http://blog.csdn.net/liumiaocn': 'bigdata',
    'http://blog.csdn.net/dream_an': 'bigdata', 'http://blog.csdn.net/yangzhenping': 'bigdata',
    'http://blog.csdn.net/afandaafandaafanda': 'bigdata', 'http://blog.csdn.net/swingwang': 'bigdata',
    'http://blog.csdn.net/zmycoco2': 'bigdata', 'http://blog.csdn.net/colorant': 'bigdata',
    'http://blog.csdn.net/a2011480169': 'bigdata', 'http://blog.csdn.net/ongoingcre': 'bigdata',
    'http://blog.csdn.net/Quincuntial': 'network', 'http://blog.csdn.net/wj903829182': 'network',
    'http://blog.csdn.net/u013709270': 'network', 'http://blog.csdn.net/u013087513': 'network',
    'http://blog.csdn.net/zhuweigangzwg': 'network', 'http://blog.csdn.net/softwave': 'network',
    'http://blog.csdn.net/u012176591': 'network', 'http://blog.csdn.net/fzxy002763': 'network',
    'http://blog.csdn.net/u010832643': 'network', 'http://blog.csdn.net/shaqoneal': 'network',
    'http://blog.csdn.net/EthanWhite': 'network', 'http://blog.csdn.net/yangyisen0713': 'network',
    'http://blog.csdn.net/force_eagle': 'network', 'http://blog.csdn.net/u012373815': 'network',
    'http://blog.csdn.net/chancein007': 'network', 'http://blog.csdn.net/dog250': 'network',
    'http://blog.csdn.net/david_520042': 'network', 'http://blog.csdn.net/lycb_gz': 'network',
    'http://blog.csdn.net/cmzsteven': 'network', 'http://blog.csdn.net/stephenxu111': 'network',
    'http://blog.csdn.net/kikitaMoon': 'network', 'http://blog.csdn.net/yming0221': 'network',
    'http://blog.csdn.net/sahusoft': 'network', 'http://blog.csdn.net/lcgweb': 'network',
    'http://blog.csdn.net/qq_35246620': 'db', 'http://blog.csdn.net/wzy0623': 'db',
    'http://blog.csdn.net/robinson_0612': 'db', 'http://blog.csdn.net/chinahuyong': 'db',
    'http://blog.csdn.net/mchdba': 'db', 'http://blog.csdn.net/leftfist': 'db',
    'http://blog.csdn.net/pan_tian': 'db', 'http://blog.csdn.net/xiangsir': 'db',
    'http://blog.csdn.net/superdont': 'db', 'http://blog.csdn.net/whinah': 'db',
    'http://blog.csdn.net/Wentasy': 'db', 'http://blog.csdn.net/renfengjun': 'db',
    'http://blog.csdn.net/you23hai45': 'frontend', 'http://blog.csdn.net/woniu1104913': 'frontend',
    'http://blog.csdn.net/powertoolsteam': 'frontend', 'http://blog.csdn.net/FungLeo': 'frontend',
    'http://blog.csdn.net/xmt1139057136': 'frontend', 'http://blog.csdn.net/sujun10': 'frontend',
    'http://blog.csdn.net/i10630226': 'frontend', 'http://blog.csdn.net/zhangxin09': 'frontend',
    'http://blog.csdn.net/yisuowushinian': 'frontend', 'http://blog.csdn.net/shi0090': 'frontend',
    'http://blog.csdn.net/JustJavaC': 'frontend', 'http://blog.csdn.net/u011043843': 'frontend',
    'http://blog.csdn.net/shuzfan': 'other', 'http://blog.csdn.net/jxw167': 'other',
    'http://blog.csdn.net/fengbingchun': 'other', 'http://blog.csdn.net/yue7603835': 'other',
    'http://blog.csdn.net/iEearth': 'other', 'http://blog.csdn.net/cabbage2008': 'other',
    'http://blog.csdn.net/foruok': 'other', 'http://blog.csdn.net/linolzhang': 'other',
    'http://blog.csdn.net/shinian1987': 'other', 'http://blog.csdn.net/weiky626': 'other',
    'http://blog.csdn.net/xjbx': 'other', 'http://blog.csdn.net/Hearthougan': 'other',
    'http://blog.csdn.net/zhangcanyan': 'mobile', 'http://blog.csdn.net/kmyhy': 'mobile',
    'http://blog.csdn.net/xiangzhihong8': 'mobile', 'http://blog.csdn.net/pangpang123654': 'mobile',
    'http://blog.csdn.net/lhc2207221755': 'mobile', 'http://blog.csdn.net/jjwwmlp456': 'mobile',
    'http://blog.csdn.net/u012124438': 'mobile', 'http://blog.csdn.net/onceing': 'mobile',
    'http://blog.csdn.net/u011012932': 'mobile', 'http://blog.csdn.net/n5': 'mobile',
    'http://blog.csdn.net/u010870518': 'mobile', 'http://blog.csdn.net/u011733020': 'mobile',
    'http://blog.csdn.net/u013970991': 'network', 'http://blog.csdn.net/forezp': 'network',
    'http://blog.csdn.net/Mr_Smile2014': 'network', 'http://blog.csdn.net/FRD2009041510': 'network',
    'http://blog.csdn.net/starshus': 'network', 'http://blog.csdn.net/u014723529': 'network',
    'http://blog.csdn.net/abv123456789': 'network', 'http://blog.csdn.net/java2000_wl': 'network',
    'http://blog.csdn.net/u010926964': 'network', 'http://blog.csdn.net/u010850027': 'network',
    'http://blog.csdn.net/WANTAWAY314': 'network', 'http://blog.csdn.net/MINEZHANGHAO': 'network',
    'http://blog.csdn.net/lipengcn': 'bigdata', 'http://blog.csdn.net/longshenlmj': 'bigdata',
    'http://blog.csdn.net/lipeng_bigdata': 'bigdata', 'http://blog.csdn.net/russell_tao': 'bigdata',
    'http://blog.csdn.net/ligaorenvip': 'bigdata', 'http://blog.csdn.net/ShaunFang': 'bigdata',
    'http://blog.csdn.net/yincheng01': 'bigdata', 'http://blog.csdn.net/liuzhoulong': 'bigdata',
    'http://blog.csdn.net/Lnho2015': 'bigdata', 'http://blog.csdn.net/Jmilk': 'bigdata',
    'http://blog.csdn.net/anzhsoft2008': 'bigdata', 'http://blog.csdn.net/cyq1984': 'bigdata',
    'http://blog.csdn.net/tianyaleixiaowu': 'network', 'http://blog.csdn.net/NNNNNNNNNNNNY': 'network',
    'http://blog.csdn.net/yutianzuijin': 'network', 'http://blog.csdn.net/lingyun2005': 'network',
    'http://blog.csdn.net/hzbooks': 'network', 'http://blog.csdn.net/wowkk': 'network',
    'http://blog.csdn.net/WinWill2012': 'network', 'http://blog.csdn.net/afatgoat': 'network',
    'http://blog.csdn.net/fredrickhu': 'network', 'http://blog.csdn.net/ZengMuAnSha': 'network',
    'http://blog.csdn.net/KimSoft': 'network', 'http://blog.csdn.net/toto1297488504': 'network',
    'http://blog.csdn.net/ctthunagchneg': 'network', 'http://blog.csdn.net/raintungli': 'network',
    'http://blog.csdn.net/smstong': 'network', 'http://blog.csdn.net/kkfloat': 'network',
    'http://blog.csdn.net/muge0913': 'network', 'http://blog.csdn.net/eroswang': 'network',
    'http://blog.csdn.net/xuyaqun': 'network', 'http://blog.csdn.net/changpei': 'network',
    'http://blog.csdn.net/sch0120': 'network', 'http://blog.csdn.net/fogyisland2000': 'network',
    'http://blog.csdn.net/ce123': 'network', 'http://blog.csdn.net/ithzhang': 'network',
    'http://blog.csdn.net/lichangzai': 'db', 'http://blog.csdn.net/huangyanlong': 'db',
    'http://blog.csdn.net/zjcxc': 'db', 'http://blog.csdn.net/wufeng4552': 'db',
    'http://blog.csdn.net/xuejiayue1105': 'db', 'http://blog.csdn.net/maco_wang': 'db',
    'http://blog.csdn.net/wuweilong': 'db', 'http://blog.csdn.net/changyanmanman': 'db',
    'http://blog.csdn.net/linghe301': 'db', 'http://blog.csdn.net/newhappy2008': 'db',
    'http://blog.csdn.net/bisal': 'db', 'http://blog.csdn.net/dongfeink': 'db',
    'http://blog.csdn.net/liangklfang': 'frontend', 'http://blog.csdn.net/hunkcai': 'frontend',
    'http://blog.csdn.net/whqet': 'frontend', 'http://blog.csdn.net/yuanziok': 'frontend',
    'http://blog.csdn.net/ligang2585116': 'frontend', 'http://blog.csdn.net/hliq5399': 'frontend',
    'http://blog.csdn.net/sunqunsunqun': 'frontend', 'http://blog.csdn.net/u012116457': 'frontend',
    'http://blog.csdn.net/woxueliuyun': 'frontend', 'http://blog.csdn.net/oLinBSoft': 'frontend',
    'http://blog.csdn.net/nayun123': 'frontend', 'http://blog.csdn.net/piperzero': 'frontend',
    'http://blog.csdn.net/ybhuangfugui': 'other', 'http://blog.csdn.net/liujian19790518': 'other',
    'http://blog.csdn.net/NK_test': 'other', 'http://blog.csdn.net/JCY58': 'other',
    'http://blog.csdn.net/youxin2012': 'other', 'http://blog.csdn.net/JoeXiongjin': 'other',
    'http://blog.csdn.net/u010825142': 'other', 'http://blog.csdn.net/hjimce': 'other',
    'http://blog.csdn.net/qhshiniba': 'other', 'http://blog.csdn.net/Testing_is_believing': 'other',
    'http://blog.csdn.net/u012192662': 'other', 'http://blog.csdn.net/jackxinxu2100': 'other',
    'http://blog.csdn.net/qq_21792169': 'mobile', 'http://blog.csdn.net/aqi00': 'mobile',
    'http://blog.csdn.net/berryreload': 'mobile', 'http://blog.csdn.net/lastsweetop': 'mobile',
    'http://blog.csdn.net/carson_ho': 'mobile', 'http://blog.csdn.net/hbblzjy': 'mobile',
    'http://blog.csdn.net/Byeweiyang': 'mobile', 'http://blog.csdn.net/u010321471': 'mobile',
    'http://blog.csdn.net/poorkick': 'mobile', 'http://blog.csdn.net/su1216': 'mobile',
    'http://blog.csdn.net/eastmoon502136': 'mobile', 'http://blog.csdn.net/yhaolpz': 'mobile',
    'http://blog.csdn.net/Leytton': 'network', 'http://blog.csdn.net/Denny_Duan77': 'network',
    'http://blog.csdn.net/zbf8441372': 'network', 'http://blog.csdn.net/yfkiss': 'network',
    'http://blog.csdn.net/liujiahan629629': 'network', 'http://blog.csdn.net/stevensxiao': 'network',
    'http://blog.csdn.net/bluishglc': 'network', 'http://blog.csdn.net/hejingyuan6': 'network',
    'http://blog.csdn.net/feixiang_john': 'network', 'http://blog.csdn.net/xiaoxian8023': 'network',
    'http://blog.csdn.net/kkk584520': 'network', 'http://blog.csdn.net/zhx6044': 'network',
    'http://blog.csdn.net/microrain': 'bigdata', 'http://blog.csdn.net/book_mmicky': 'bigdata',
    'http://blog.csdn.net/Gamer_gyt': 'bigdata', 'http://blog.csdn.net/lovehuangjiaju': 'bigdata',
    'http://blog.csdn.net/quqi99': 'bigdata', 'http://blog.csdn.net/wanweiaiaqiang': 'bigdata',
    'http://blog.csdn.net/robertlee32': 'bigdata', 'http://blog.csdn.net/yanheven1': 'bigdata',
    'http://blog.csdn.net/babyfacer': 'bigdata', 'http://blog.csdn.net/gshengod': 'bigdata',
    'http://blog.csdn.net/halcyonbaby': 'bigdata', 'http://blog.csdn.net/zhang5476499': 'network',
    'http://blog.csdn.net/changemyself': 'network', 'http://blog.csdn.net/catoop': 'network',
    'http://blog.csdn.net/tanaya': 'network', 'http://blog.csdn.net/jhzyz': 'network',
    'http://blog.csdn.net/wangqiuyun': 'network', 'http://blog.csdn.net/tiandijun': 'network',
    'http://blog.csdn.net/xiaocaiju': 'network', 'http://blog.csdn.net/beliefer': 'network',
    'http://blog.csdn.net/MSSecurity': 'network', 'http://blog.csdn.net/sunbaigui': 'network',
    'http://blog.csdn.net/xukai871105': 'network', 'http://blog.csdn.net/upi2u': 'network',
    'http://blog.csdn.net/xiahouzuoxin': 'network', 'http://blog.csdn.net/zhanghongju': 'db',
    'http://blog.csdn.net/t0nsha': 'db', 'http://blog.csdn.net/magenfeng': 'db',
    'http://blog.csdn.net/guoyJoe': 'db', 'http://blog.csdn.net/l106439814': 'db',
    'http://blog.csdn.net/FS1360472174': 'db', 'http://blog.csdn.net/wangjian5748': 'db',
    'http://blog.csdn.net/tianlesoftware': 'db', 'http://blog.csdn.net/ghostliming': 'db',
    'http://blog.csdn.net/fly2nn': 'db', 'http://blog.csdn.net/robinson1988': 'db',
    'http://blog.csdn.net/sunansheng': 'db', 'http://blog.csdn.net/GISpace': 'frontend',
    'http://blog.csdn.net/milado_nju': 'frontend', 'http://blog.csdn.net/kongki': 'frontend',
    'http://blog.csdn.net/xllily_11': 'frontend', 'http://blog.csdn.net/yizhu2000': 'frontend',
    'http://blog.csdn.net/fareise': 'frontend', 'http://blog.csdn.net/lzhlzz': 'frontend',
    'http://blog.csdn.net/yulei_qq': 'frontend', 'http://blog.csdn.net/itpinpai': 'frontend',
    'http://blog.csdn.net/bomess': 'frontend', 'http://blog.csdn.net/baozhengw': 'frontend',
    'http://blog.csdn.net/linyustar': 'frontend', 'http://blog.csdn.net/taigw': 'other',
    'http://blog.csdn.net/sinat_26917383': 'other', 'http://blog.csdn.net/qingrun': 'other',
    'http://blog.csdn.net/sportshark': 'other', 'http://blog.csdn.net/shenyisyn': 'other',
    'http://blog.csdn.net/coolbacon': 'other', 'http://blog.csdn.net/SoftwareTeacher': 'other',
    'http://blog.csdn.net/dongdong9223': 'other', 'http://blog.csdn.net/david_lv': 'other',
    'http://blog.csdn.net/hzliyun': 'other', 'http://blog.csdn.net/dellfox': 'other',
    'http://blog.csdn.net/heyijia0327': 'other', 'http://blog.csdn.net/hekaiyou': 'mobile',
    'http://blog.csdn.net/leonwei': 'mobile', 'http://blog.csdn.net/linyt': 'mobile',
    'http://blog.csdn.net/fzhlee': 'mobile', 'http://blog.csdn.net/lfdfhl': 'mobile',
    'http://blog.csdn.net/openglnewbee': 'mobile', 'http://blog.csdn.net/fengyuzhengfan': 'mobile',
    'http://blog.csdn.net/github_33304260': 'mobile', 'http://blog.csdn.net/fox64194167': 'mobile',
    'http://blog.csdn.net/qq_30379689': 'mobile', 'http://blog.csdn.net/zxm317122667': 'mobile',
    'http://blog.csdn.net/u010844111': 'network', 'http://blog.csdn.net/jason_dct': 'network',
    'http://blog.csdn.net/lynnlovemin': 'network', 'http://blog.csdn.net/analogous_love': 'network',
    'http://blog.csdn.net/JThink_': 'network', 'http://blog.csdn.net/BugRunner': 'network',
    'http://blog.csdn.net/qq_30739519': 'network', 'http://blog.csdn.net/yinwenjie': 'network',
    'http://blog.csdn.net/xieyuooo': 'network', 'http://blog.csdn.net/ycg514230': 'network',
    'http://blog.csdn.net/coffeewoo': 'network', 'http://blog.csdn.net/nsrainbow': 'bigdata',
    'http://blog.csdn.net/jiangshouzhuang': 'bigdata', 'http://blog.csdn.net/u014388509': 'bigdata',
    'http://blog.csdn.net/BlueCloudMatrix': 'bigdata', 'http://blog.csdn.net/sunbow0': 'bigdata',
    'http://blog.csdn.net/jiq408694711': 'bigdata', 'http://blog.csdn.net/LXYTSOS': 'bigdata',
    'http://blog.csdn.net/u012798391': 'bigdata', 'http://blog.csdn.net/JavaMan_chen': 'bigdata',
    'http://blog.csdn.net/accesine960': 'bigdata', 'http://blog.csdn.net/horsefoot': 'bigdata',
    'http://blog.csdn.net/ex_net': 'network', 'http://blog.csdn.net/xinzhangyanxiang': 'network',
    'http://blog.csdn.net/chaishen10000': 'network', 'http://blog.csdn.net/nuoline': 'network',
    'http://blog.csdn.net/shaokun305': 'network', 'http://blog.csdn.net/yangliuy': 'network',
    'http://blog.csdn.net/xifeijian': 'network', 'http://blog.csdn.net/u010255642': 'network',
    'http://blog.csdn.net/jirongzi_cs2011': 'network', 'http://blog.csdn.net/jiangtao': 'network',
    'http://blog.csdn.net/yaoqiang2011': 'network', 'http://blog.csdn.net/wonder4': 'db',
    'http://blog.csdn.net/linwaterbin': 'db', 'http://blog.csdn.net/iihero': 'db',
    'http://blog.csdn.net/DBA_Huangzj': 'db', 'http://blog.csdn.net/tuzongxun': 'db',
    'http://blog.csdn.net/lukeUnique': 'db', 'http://blog.csdn.net/GISShiXiSheng': 'frontend',
    'http://blog.csdn.net/kkkkkxiaofei': 'frontend', 'http://blog.csdn.net/qq_26525215': 'frontend',
    'http://blog.csdn.net/zhang__tianxu': 'frontend', 'http://blog.csdn.net/gmszone': 'frontend',
    'http://blog.csdn.net/xuexiaodong2009': 'frontend', 'http://blog.csdn.net/qianlong4526888': 'other',
    'http://blog.csdn.net/babyblue_963': 'other', 'http://blog.csdn.net/leezy_2000': 'other',
    'http://blog.csdn.net/liuqiyao_01': 'other', 'http://blog.csdn.net/HAPPENgft': 'other',
    'http://blog.csdn.net/downmoon': 'other', 'http://blog.csdn.net/compassbutton': 'other',
    'http://blog.csdn.net/jiayanhui2877': 'other', 'http://blog.csdn.net/lilongsheng1125': 'other',
    'http://blog.csdn.net/zzlyw': 'other', 'http://blog.csdn.net/hongshan50': 'other',
    'http://blog.csdn.net/honghaier': 'other', 'http://blog.csdn.net/new_abc': 'mobile',
    'http://blog.csdn.net/qiujuer': 'mobile', 'http://blog.csdn.net/qq_16064871': 'mobile',
    'http://blog.csdn.net/u014738140': 'mobile', 'http://blog.csdn.net/iwanghang': 'mobile',
    'http://blog.csdn.net/THEONE10211024': 'mobile', 'http://blog.csdn.net/u011913612': 'mobile',
    'http://blog.csdn.net/jiangwei0910410003': 'mobile', 'http://blog.csdn.net/linshuhe1': 'mobile',
    'http://blog.csdn.net/21cnbao': 'mobile', 'http://blog.csdn.net/Gaugamela': 'mobile',
    'http://blog.csdn.net/shineflowers': 'mobile', 'http://blog.csdn.net/ityouknow': 'network',
    'http://blog.csdn.net/YuLimin': 'network', 'http://blog.csdn.net/gatieme': 'network',
    'http://blog.csdn.net/xbinworld': 'network', 'http://blog.csdn.net/hopeztm': 'network',
    'http://blog.csdn.net/kkdelta': 'network', 'http://blog.csdn.net/yah99_wolf': 'network',
    'http://blog.csdn.net/dinglang_2009': 'network', 'http://blog.csdn.net/m13666368773': 'network',
    'http://blog.csdn.net/leecho571': 'network', 'http://blog.csdn.net/xiamizy': 'network',
    'http://blog.csdn.net/mao0514': 'network', 'http://blog.csdn.net/yeweiouyang': 'bigdata',
    'http://blog.csdn.net/TonyShengTan': 'bigdata', 'http://blog.csdn.net/u010170023': 'bigdata',
    'http://blog.csdn.net/longxinchen_ml': 'bigdata', 'http://blog.csdn.net/fansy1990': 'bigdata',
    'http://blog.csdn.net/feiskyer': 'bigdata', 'http://blog.csdn.net/xuhuojun': 'bigdata',
    'http://blog.csdn.net/qcpm1983': 'bigdata', 'http://blog.csdn.net/dabokele': 'bigdata',
    'http://blog.csdn.net/sky_walker85': 'bigdata', 'http://blog.csdn.net/iamonlyme': 'bigdata',
    'http://blog.csdn.net/cnsword': 'bigdata', 'http://blog.csdn.net/tobacco5648': 'network',
    'http://blog.csdn.net/cndes': 'network', 'http://blog.csdn.net/diehuan2008': 'network',
    'http://blog.csdn.net/felomeng': 'network', 'http://blog.csdn.net/google19890102': 'network',
    'http://blog.csdn.net/jiang1st2010': 'network', 'http://blog.csdn.net/silencemylove': 'network',
    'http://blog.csdn.net/dc_726': 'network', 'http://blog.csdn.net/yangbutao': 'network',
    'http://blog.csdn.net/pangjiuzala': 'network', 'http://blog.csdn.net/cnbragon': 'network',
    'http://blog.csdn.net/zhoubl668': 'network', 'http://blog.csdn.net/kongqz': 'other',
    'http://blog.csdn.net/pukuimin1226': 'other', 'http://blog.csdn.net/duan_zhihua': 'other',
    'http://blog.csdn.net/harrymeng': 'other', 'http://blog.csdn.net/Bone_ACE': 'other',
    'http://blog.csdn.net/zhouxuguang236': 'other', 'http://blog.csdn.net/zhangmike': 'other',
    'http://blog.csdn.net/Raptor': 'other', 'http://blog.csdn.net/caixingyun': 'other',
    'http://blog.csdn.net/dylanren': 'other', 'http://blog.csdn.net/blueheart20': 'other',
    'http://blog.csdn.net/liangjingbo': 'other', 'http://blog.csdn.net/wuyinlei': 'mobile',
    'http://blog.csdn.net/briblue': 'mobile', 'http://blog.csdn.net/abcamus': 'mobile',
    'http://blog.csdn.net/lisdye2': 'mobile', 'http://blog.csdn.net/a396901990': 'mobile',
    'http://blog.csdn.net/u011974987': 'mobile', 'http://blog.csdn.net/zhangke3016': 'mobile',
    'http://blog.csdn.net/zhanggang740': 'mobile', 'http://blog.csdn.net/CSDN_LQR': 'mobile',
    'http://blog.csdn.net/xyang81': 'mobile', 'http://blog.csdn.net/chunqiuwei': 'mobile',
    'http://blog.csdn.net/jiangcaiyang123': 'mobile', 'http://blog.csdn.net/CXXSoft': 'network',
    'http://blog.csdn.net/flydream0': 'network', 'http://blog.csdn.net/bywayboy': 'network',
    'http://blog.csdn.net/fenglibing': 'network', 'http://blog.csdn.net/shimiso': 'network',
    'http://blog.csdn.net/zssureqh': 'network', 'http://blog.csdn.net/kylinsoong': 'network',
    'http://blog.csdn.net/normalnotebook': 'network', 'http://blog.csdn.net/useway': 'network',
    'http://blog.csdn.net/zbc1090549839': 'network', 'http://blog.csdn.net/chijianqiang': 'network',
    'http://blog.csdn.net/chaijunkun': 'network', 'http://blog.csdn.net/lsshlsw': 'bigdata',
    'http://blog.csdn.net/zuoxiaolong8810': 'bigdata', 'http://blog.csdn.net/zhangskd': 'bigdata',
    'http://blog.csdn.net/hawksoft': 'bigdata', 'http://blog.csdn.net/imfly': 'bigdata',
    'http://blog.csdn.net/pipisorry': 'bigdata', 'http://blog.csdn.net/gaoxingnengjisuan': 'bigdata',
    'http://blog.csdn.net/azurechina': 'bigdata', 'http://blog.csdn.net/yueliangdao0608': 'network',
    'http://blog.csdn.net/kthq': 'network', 'http://blog.csdn.net/freewebsys': 'network',
    'http://blog.csdn.net/wangyang1354': 'network', 'http://blog.csdn.net/superch0054': 'network',
    'http://blog.csdn.net/eson_15': 'network', 'http://blog.csdn.net/chenyusiyuan': 'network',
    'http://blog.csdn.net/malefactor': 'network', 'http://blog.csdn.net/ioio_jy': 'network',
    'http://blog.csdn.net/HorkyChen': 'network', 'http://blog.csdn.net/liyuanxiang1984': 'other',
    'http://blog.csdn.net/wxcdzhangping': 'other', 'http://blog.csdn.net/violet200211': 'other',
    'http://blog.csdn.net/Solstice': 'other', 'http://blog.csdn.net/jiangguilong2000': 'other',
    'http://blog.csdn.net/pmpgao': 'other', 'http://blog.csdn.net/gsying1474': 'other',
    'http://blog.csdn.net/scorpio3k': 'other', 'http://blog.csdn.net/cheny_com': 'other',
    'http://blog.csdn.net/nanjingjiangbiao': 'other', 'http://blog.csdn.net/happydeer': 'other',
    'http://blog.csdn.net/jinhill': 'other', 'http://blog.csdn.net/zpj779878443': 'mobile',
    'http://blog.csdn.net/XSF50717': 'mobile', 'http://blog.csdn.net/wdong_love_cl': 'mobile',
    'http://blog.csdn.net/liuxian13183': 'mobile', 'http://blog.csdn.net/zhaoxy2850': 'mobile',
    'http://blog.csdn.net/gdky005': 'mobile', 'http://blog.csdn.net/gengqiquan': 'mobile',
    'http://blog.csdn.net/tangxiaoyin': 'mobile', 'http://blog.csdn.net/linyongan': 'mobile',
    'http://blog.csdn.net/xgbing': 'mobile', 'http://blog.csdn.net/lifetragedy': 'network',
    'http://blog.csdn.net/u012025054': 'network', 'http://blog.csdn.net/hsbirenjie': 'network',
    'http://blog.csdn.net/ziwen00': 'network', 'http://blog.csdn.net/ronghao100': 'network',
    'http://blog.csdn.net/u012345283': 'network', 'http://blog.csdn.net/Poechant': 'network',
    'http://blog.csdn.net/jiuqiyuliang': 'network', 'http://blog.csdn.net/JaCman': 'network',
    'http://blog.csdn.net/s003603u': 'mobile', 'http://blog.csdn.net/weidi1989': 'mobile',
    'http://blog.csdn.net/JspAndAsp': 'mobile', 'http://blog.csdn.net/wireless_com': 'mobile',
    'http://blog.csdn.net/aa4790139': 'mobile', 'http://blog.csdn.net/King1425': 'mobile',
    'http://blog.csdn.net/Kaitiren': 'mobile', 'http://blog.csdn.net/tangcheng_ok': 'mobile',
    'http://blog.csdn.net/u012551350': 'mobile', 'http://blog.csdn.net/strawberry2013': 'mobile',
    'http://blog.csdn.net/p106786860': 'mobile', 'http://blog.csdn.net/yueqian_scut': 'mobile',
    'http://blog.csdn.net/hellochina15': 'network', 'http://blog.csdn.net/cuiran': 'network',
    'http://blog.csdn.net/ioriliao': 'network', 'http://blog.csdn.net/a600423444': 'network',
    'http://blog.csdn.net/undoner': 'network', 'http://blog.csdn.net/lishehe': 'network',
    'http://blog.csdn.net/bojie5744': 'network', 'http://blog.csdn.net/lightseed': 'network',
    'http://blog.csdn.net/beijiguangyong': 'network', 'http://blog.csdn.net/starrow': 'network',
    'http://blog.csdn.net/hjx_1000': 'network', 'http://blog.csdn.net/ihrthk': 'mobile',
    'http://blog.csdn.net/lowprofile_coding': 'mobile', 'http://blog.csdn.net/nokiaguy': 'mobile',
    'http://blog.csdn.net/angcyo': 'mobile', 'http://blog.csdn.net/aomandeshangxiao': 'mobile',
    'http://blog.csdn.net/ynnmnm': 'mobile', 'http://blog.csdn.net/feng88724': 'mobile',
    'http://blog.csdn.net/qq_26787115': 'mobile', 'http://blog.csdn.net/itachi85': 'mobile',
    'http://blog.csdn.net/ustc_dylan': 'network', 'http://blog.csdn.net/oDaiLiDong': 'network',
    'http://blog.csdn.net/e421083458': 'network', 'http://blog.csdn.net/aofengdaxia': 'network',
    'http://blog.csdn.net/u011387207': 'network', 'http://blog.csdn.net/kkkloveyou': 'network',
    'http://blog.csdn.net/langeldep': 'network', 'http://blog.csdn.net/rill_zhen': 'network',
    'http://blog.csdn.net/shootyou': 'network', 'http://blog.csdn.net/jhq0113': 'network',
    'http://blog.csdn.net/dlf123321': 'network', 'http://blog.csdn.net/u010785585': 'mobile',
    'http://blog.csdn.net/musicvs': 'mobile', 'http://blog.csdn.net/yissan': 'mobile',
    'http://blog.csdn.net/a345017062': 'mobile', 'http://blog.csdn.net/yywan1314520': 'mobile',
    'http://blog.csdn.net/liaoinstan': 'mobile', 'http://blog.csdn.net/junzia': 'mobile',
    'http://blog.csdn.net/javazejian': 'mobile', 'http://blog.csdn.net/song19891121': 'mobile',
    'http://blog.csdn.net/jasonblog': 'mobile', 'http://blog.csdn.net/jdh99': 'mobile',
    'http://blog.csdn.net/chgaowei': 'network', 'http://blog.csdn.net/qq_22520587': 'network',
    'http://blog.csdn.net/livelylittlefish': 'network', 'http://blog.csdn.net/mynameishuangshuai': 'mobile',
    'http://blog.csdn.net/zinss26914': 'mobile', 'http://blog.csdn.net/jijiaxin1989': 'mobile',
    'http://blog.csdn.net/kakashi8841': 'mobile', 'http://blog.csdn.net/hherima': 'mobile',
    'http://blog.csdn.net/qq_21430549': 'mobile', 'http://blog.csdn.net/bz419927089': 'mobile',
    'http://blog.csdn.net/wxg694175346': 'mobile', 'http://blog.csdn.net/zhenwenxian': 'mobile',
    'http://blog.csdn.net/miloyip': 'mobile', 'http://blog.csdn.net/zuiwuyuan': 'mobile',
    'http://blog.csdn.net/keyboardOTA': 'mobile', 'http://blog.csdn.net/HHL110120': 'mobile',
    'http://blog.csdn.net/bill_man': 'mobile', 'http://blog.csdn.net/vfush': 'mobile',
    'http://blog.csdn.net/Amazing7': 'mobile', 'http://blog.csdn.net/niubitianping': 'mobile',
    'http://blog.csdn.net/qq446569365': 'mobile', 'http://blog.csdn.net/jianxin160': 'mobile',
    'http://blog.csdn.net/Android_Tutor': 'mobile', 'http://blog.csdn.net/RowandJJ': 'mobile',
    'http://blog.csdn.net/humingtao2013': 'mobile', 'http://blog.csdn.net/u012702547': 'mobile',
    'http://blog.csdn.net/asd1031': 'mobile', 'http://blog.csdn.net/stven_king': 'mobile',
    'http://blog.csdn.net/yulianlin': 'mobile', 'http://blog.csdn.net/zpf8861': 'mobile',
    'http://blog.csdn.net/anddlecn': 'mobile', 'http://blog.csdn.net/cloudhsu': 'mobile',
    'http://blog.csdn.net/sundesheng125': 'mobile', 'http://blog.csdn.net/ysy441088327': 'mobile',
    'http://blog.csdn.net/wangjinyu501': 'mobile', 'http://blog.csdn.net/jaikydota163': 'mobile',
    'http://blog.csdn.net/nugongahou110': 'mobile', 'http://blog.csdn.net/kesalin': 'mobile',
    'http://blog.csdn.net/sbsujjbcy': 'mobile', 'http://blog.csdn.net/cuibo1123': 'mobile',
    'http://blog.csdn.net/wenbitianxiafeng': 'mobile', 'http://blog.csdn.net/Luoshengyang': 'mobile',
    'http://blog.csdn.net/cym492224103': 'mobile', 'http://blog.csdn.net/jwzhangjie': 'mobile',
    'http://blog.csdn.net/cp790621656': 'mobile', 'http://blog.csdn.net/arui319': 'mobile',
    'http://blog.csdn.net/xx326664162': 'mobile', 'http://blog.csdn.net/lmj623565791': 'mobile',
    'http://blog.csdn.net/loongggdroid': 'mobile', 'http://blog.csdn.net/dmk877': 'mobile',
    'http://blog.csdn.net/lyhhj': 'mobile', 'http://blog.csdn.net/u010163442': 'mobile',
    'http://blog.csdn.net/maosidiaoxian': 'mobile', 'http://blog.csdn.net/wdaming1986': 'mobile',
    'http://blog.csdn.net/yangdeli888': 'mobile', 'http://blog.csdn.net/leejizhou': 'mobile',
    'http://blog.csdn.net/u010019717': 'mobile', 'http://blog.csdn.net/lxq_xsyu': 'mobile',
    'http://blog.csdn.net/rain_butterfly': 'mobile', 'http://blog.csdn.net/chenjie19891104': 'mobile',
    'http://blog.csdn.net/baiyuliang2013': 'mobile', 'http://blog.csdn.net/u014610664': 'mobile',
    'http://blog.csdn.net/sdkfjksf': 'mobile', 'http://blog.csdn.net/IT_DS': 'mobile',
    'http://blog.csdn.net/sw950729': 'mobile', 'http://blog.csdn.net/w337198302': 'mobile',
    'http://blog.csdn.net/shencaifeixia1': 'mobile', 'http://blog.csdn.net/robertcpp': 'mobile',
    'http://blog.csdn.net/wangk1026': 'mobile', 'http://blog.csdn.net/fengsh998': 'mobile',
    'http://blog.csdn.net/AndrewFan': 'mobile', 'http://blog.csdn.net/qq_31810357': 'mobile',
    'http://blog.csdn.net/jspping': 'mobile', 'http://blog.csdn.net/a631855639': 'mobile',
    'http://blog.csdn.net/swj524152416': 'mobile', 'http://blog.csdn.net/jltxgcy': 'mobile',
    'http://blog.csdn.net/yang8456211': 'mobile', 'http://blog.csdn.net/jackyvincefu': 'mobile',
    'http://blog.csdn.net/gzzaigcn': 'mobile', 'http://blog.csdn.net/jxt1234and2010': 'mobile',
    'http://blog.csdn.net/qq992817263': 'mobile', 'http://blog.csdn.net/cordova': 'mobile',
    'http://blog.csdn.net/hitlion2008': 'mobile', 'http://blog.csdn.net/zyq522376829': 'mobile',
    'http://blog.csdn.net/mabeijianxi': 'mobile', 'http://blog.csdn.net/u011064099': 'mobile',
    'http://blog.csdn.net/yayun0516': 'mobile', 'http://blog.csdn.net/aaawqqq': 'mobile',
    'http://blog.csdn.net/sk719887916': 'mobile', 'http://blog.csdn.net/DLUTBruceZhang': 'mobile',
    'http://blog.csdn.net/u014427391': 'mobile', 'http://blog.csdn.net/mapdigit': 'mobile',
    'http://blog.csdn.net/chenzujie': 'mobile', 'http://blog.csdn.net/qwm8777411': 'mobile',
    'http://blog.csdn.net/xiaohanluo': 'mobile', 'http://blog.csdn.net/SEU_Calvin': 'mobile',
    'http://blog.csdn.net/FeeLang': 'mobile', 'http://blog.csdn.net/wangzi11322': 'mobile',
    'http://blog.csdn.net/u011619283': 'mobile', 'http://blog.csdn.net/CHENYUFENG1991': 'mobile',
    'http://blog.csdn.net/u013900875': 'mobile', 'http://blog.csdn.net/mydo': 'mobile',
    'http://blog.csdn.net/NUPTboyZHB': 'mobile', 'http://blog.csdn.net/yzzst': 'mobile',
    'http://blog.csdn.net/huangbiao86': 'mobile', 'http://blog.csdn.net/yanghuiliu': 'mobile',
    'http://blog.csdn.net/shenjie12345678': 'mobile', 'http://blog.csdn.net/yuanzeyao2008': 'mobile',
    'http://blog.csdn.net/yanbober': 'mobile', 'http://blog.csdn.net/caihongshijie6': 'mobile',
    'http://blog.csdn.net/luopingfeng': 'mobile', 'http://blog.csdn.net/hejjunlin': 'mobile',
    'http://blog.csdn.net/htq__': 'mobile', 'http://blog.csdn.net/jdsjlzx': 'mobile',
    'http://blog.csdn.net/jason0539': 'mobile', 'http://blog.csdn.net/hanhailong726188': 'mobile',
    'http://blog.csdn.net/BossDarcy': 'mobile', 'http://blog.csdn.net/mengxiangyue': 'mobile',
    'http://blog.csdn.net/qxs965266509': 'mobile', 'http://blog.csdn.net/txw1958': 'mobile',
    'http://blog.csdn.net/qq_22063697': 'mobile', 'http://blog.csdn.net/LeoLeoHan': 'mobile',
    'http://blog.csdn.net/Hebin320320': 'mobile', 'http://blog.csdn.net/m_052148': 'mobile',
    'http://blog.csdn.net/BaiHuaXiu123': 'mobile', 'http://blog.csdn.net/kangaroo835127729': 'mobile',
    'http://blog.csdn.net/wingichoy': 'mobile', 'http://blog.csdn.net/fansongy': 'mobile',
    'http://blog.csdn.net/u013357243': 'mobile', 'http://blog.csdn.net/wh1990xiao2005': 'mobile',
    'http://blog.csdn.net/Hello_Hwc': 'mobile', 'http://blog.csdn.net/a910626': 'mobile',
    'http://blog.csdn.net/relicemxd': 'mobile', 'http://blog.csdn.net/qibin0506': 'mobile',
    'http://blog.csdn.net/sleks': 'mobile', 'http://blog.csdn.net/nkmnkm': 'mobile',
    'http://blog.csdn.net/xiaominghimi': 'mobile', 'http://blog.csdn.net/qq_17250009': 'mobile',
    'http://blog.csdn.net/yuanguozhengjust': 'mobile', 'http://blog.csdn.net/sunhuaqiang1': 'mobile',
    'http://blog.csdn.net/u011133213': 'mobile', 'http://blog.csdn.net/sinat_30162391': 'mobile',
    'http://blog.csdn.net/cuit': 'mobile', 'http://blog.csdn.net/qfanmingyiq': 'mobile',
    'http://blog.csdn.net/likendsl': 'mobile', 'http://blog.csdn.net/qp120291570': 'mobile',
    'http://blog.csdn.net/hfahe': 'mobile', 'http://blog.csdn.net/lwj103862095': 'mobile',
    'http://blog.csdn.net/lyq8479': 'mobile', 'http://blog.csdn.net/mr_raptor': 'mobile',
    'http://blog.csdn.net/rootusers': 'mobile', 'http://blog.csdn.net/t12x3456': 'mobile',
    'http://blog.csdn.net/blogercn': 'mobile', 'http://blog.csdn.net/manoel': 'mobile',
    'http://blog.csdn.net/han1202012': 'mobile', 'http://blog.csdn.net/GooHong': 'mobile',
    'http://blog.csdn.net/gao_chun': 'mobile', 'http://blog.csdn.net/yyh352091626': 'mobile',
    'http://blog.csdn.net/LoongEmbedded': 'mobile', 'http://blog.csdn.net/my183100521': 'mobile',
    'http://blog.csdn.net/Innost': 'mobile', 'http://blog.csdn.net/qq285016127': 'mobile',
    'http://blog.csdn.net/u014608640': 'mobile', 'http://blog.csdn.net/u013278099': 'mobile',
    'http://blog.csdn.net/johnny901114': 'mobile', 'http://blog.csdn.net/u011310942': 'mobile',
    'http://blog.csdn.net/q4878802': 'mobile', 'http://blog.csdn.net/qq_32059827': 'mobile',
    'http://blog.csdn.net/sodino': 'mobile', 'http://blog.csdn.net/a332324956': 'mobile',
    'http://blog.csdn.net/mmoaay': 'mobile', 'http://blog.csdn.net/totogo2010': 'mobile',
    'http://blog.csdn.net/ddwhan0123': 'mobile', 'http://blog.csdn.net/jiangqq781931404': 'mobile',
    'http://blog.csdn.net/caowenbin': 'mobile', 'http://blog.csdn.net/Yt7589': 'mobile',
    'http://blog.csdn.net/VNanyesheshou': 'mobile', 'http://blog.csdn.net/googdev': 'mobile',
    'http://blog.csdn.net/smartbetter': 'mobile', 'http://blog.csdn.net/x359981514': 'mobile',
    'http://blog.csdn.net/ljd2038': 'mobile', 'http://blog.csdn.net/jinhuoxingkong': 'mobile',
    'http://blog.csdn.net/SuperBigLw': 'mobile', 'http://blog.csdn.net/s10141303': 'mobile',
    'http://blog.csdn.net/fengyarongaa': 'mobile', 'http://blog.csdn.net/ElinaVampire': 'mobile',
    'http://blog.csdn.net/ys743276112': 'mobile', 'http://blog.csdn.net/songrotek': 'mobile',
    'http://blog.csdn.net/yiyaaixuexi': 'mobile', 'http://blog.csdn.net/ccpat': 'mobile',
    'http://blog.csdn.net/singwhatiwanna': 'mobile', 'http://blog.csdn.net/pzhtpf': 'mobile',
    'http://blog.csdn.net/ameyume': 'mobile', 'http://blog.csdn.net/lincyang': 'mobile',
    'http://blog.csdn.net/DJY1992': 'mobile', 'http://blog.csdn.net/zrf1335348191': 'mobile',
    'http://blog.csdn.net/u010687392': 'mobile', 'http://blog.csdn.net/qq_15950325': 'mobile',
    'http://blog.csdn.net/u012945598': 'mobile', 'http://blog.csdn.net/zyw_java': 'mobile',
    'http://blog.csdn.net/banketree': 'mobile', 'http://blog.csdn.net/ocean20': 'mobile',
    'http://blog.csdn.net/hursing': 'mobile', 'http://blog.csdn.net/feiyinzilgd': 'mobile',
    'http://blog.csdn.net/ostrichmyself': 'mobile', 'http://blog.csdn.net/qq_23547831': 'mobile',
    'http://blog.csdn.net/Greathfs': 'mobile', 'http://blog.csdn.net/pucker': 'mobile',
    'http://blog.csdn.net/duanyipeng': 'mobile', 'http://blog.csdn.net/ugg': 'mobile',
    'http://blog.csdn.net/zay109327402': 'mobile', 'http://blog.csdn.net/hitwhylz': 'mobile',
    'http://blog.csdn.net/qinxiandiqi': 'mobile', 'http://blog.csdn.net/typename': 'mobile',
    'http://blog.csdn.net/wang631106979': 'mobile', 'http://blog.csdn.net/u013045971': 'mobile',
    'http://blog.csdn.net/luoyanglizi': 'mobile', 'http://blog.csdn.net/shakespeare001': 'mobile',
    'http://blog.csdn.net/zqiang_55': 'mobile', 'http://blog.csdn.net/huachao1001': 'mobile',
    'http://blog.csdn.net/NoMasp': 'mobile', 'http://blog.csdn.net/iefreer': 'mobile',
    'http://blog.csdn.net/L173864930': 'mobile', 'http://blog.csdn.net/heartrude': 'mobile',
    'http://blog.csdn.net/bdmh': 'mobile', 'http://blog.csdn.net/cauchyweierstrass': 'mobile',
    'http://blog.csdn.net/dd864140130': 'mobile', 'http://blog.csdn.net/harvic880925': 'mobile',
    'http://blog.csdn.net/NiZhuanXingHeIT': 'mobile', 'http://blog.csdn.net/liyuanjinglyj': 'mobile',
    'http://blog.csdn.net/xyz_lmn': 'mobile', 'http://blog.csdn.net/songjinshi': 'mobile',
    'http://blog.csdn.net/zhangao0086': 'mobile', 'http://blog.csdn.net/w7849516230': 'mobile',
    'http://blog.csdn.net/xubin341719': 'mobile'
}

segmentfault_urls = {
    'https://segmentfault.com/t/python/blogs': 'backend',
    'https://segmentfault.com/t/javascript/blogs': 'frontend',
    'https://segmentfault.com/t/php/blogs': 'backend',
    'https://segmentfault.com/t/java/blogs': 'backend',
    'https://segmentfault.com/t/mysql/blogs': 'db',
    'https://segmentfault.com/t/ios/blogs': 'mobile',
    'https://segmentfault.com/t/android/blogs': 'mobile',
    'https://segmentfault.com/t/node.js/blogs': 'backend',
    'https://segmentfault.com/t/html5/blogs': 'frontend',
    'https://segmentfault.com/t/linux/blogs': 'os',
    'https://segmentfault.com/t/c%2B%2B/blogs': 'backend',
    'https://segmentfault.com/t/css3/blogs': 'frontend',
    'https://segmentfault.com/t/git/blogs': 'os',
    'https://segmentfault.com/t/golang/blogs': 'backend',
    'https://segmentfault.com/t/ruby/blogs': 'backend',
    'https://segmentfault.com/t/vim/blogs': 'os',
    'https://segmentfault.com/t/docker/blogs': 'os',
    'https://segmentfault.com/t/mongodb/blogs': 'db',
}

cto56_urls = {
    'http://www.56cto.com/category/yunwei': 'network',
    'http://www.56cto.com/category/network': 'network',
    'http://www.56cto.com/category/cloud': 'bigdata',
    'http://www.56cto.com/category/download': 'other',
    'http://www.56cto.com/category/kandian': 'news',
    'http://www.56cto.com/category/job': 'other',
}

cnblogs_urls = {
    'http://www.cnblogs.com/linbc/': 'os',
}

mamicode_urls = {
    'http://www.mamicode.com/info-list-2-1.html': 'frontend',
    'http://www.mamicode.com/info-list-3-1.html': 'os',
    'http://www.mamicode.com/info-list-4-1.html': 'backend',
    'http://www.mamicode.com/info-list-5-1.html': 'db',
    'http://www.mamicode.com/info-list-6-1.html': 'mobile',
    'http://www.mamicode.com/info-list-8-1.html': 'os',
    'http://www.mamicode.com/info-list-9-1.html': 'other',
    'http://www.mamicode.com/info-list-11-1.html': 'other',
}
